name: Custom Client Build

on:
  workflow_dispatch:
    inputs:
      config_ids:
        description: 'Comma-separated list of configuration IDs to build for (leave empty for all)'
        required: false
        default: ''
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'librechat-config/custom-styles/**'

jobs:
  determine-configs:
    runs-on: ubuntu-latest
    outputs:
      config-matrix: ${{ steps.set-matrix.outputs.config-matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: aproorg/librechat-config
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set configuration matrix
        id: set-matrix
        run: |
          if [ -n "${{ github.event.inputs.config_ids }}" ]; then
            # Use manually specified configuration IDs
            CONFIGS=$(echo "${{ github.event.inputs.config_ids }}" | tr ',' '\n' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          else
            # Discover configurations from directory structure
            CONFIGS=$(find custom-styles -mindepth 1 -maxdepth 1 -type d | sed 's|custom-styles/||' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          fi
          echo "config-matrix=${CONFIGS}" >> $GITHUB_OUTPUT

  build-client:
    needs: determine-configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config_id: ${{ fromJson(needs.determine-configs.outputs.config-matrix) }}
    steps:
      - name: Checkout LibreChat
        uses: actions/checkout@v4
        with:
          repository: aproorg/LibreChat
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout librechat-config
        uses: actions/checkout@v4
        with:
          repository: aproorg/librechat-config
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ../librechat-config
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Prepare custom CSS
        run: |
          cd client
          mkdir -p src/styles
          cp ../librechat-config/custom-styles/${{ matrix.config_id }}/css/style.css src/styles/custom.css
          
      - name: Build client with custom styling
        env:
          CONFIG_ID: ${{ matrix.config_id }}
          POSTCSS_CONFIG_PATH: './scripts/custom-styling/postcss.config.wrapper.js'
        run: |
          cd client
          npm ci
          npm run build
          
      - name: Upload client build
        uses: actions/upload-artifact@v4
        with:
          name: librechat-client-${{ matrix.config_id }}
          path: client/dist/${{ matrix.config_id || 'default' }}
          retention-days: 7
