name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::533267242259:role/github-oidc-genai
          aws-region: eu-west-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=latest
          API_REPOSITORY_URI=533267242259.dkr.ecr.eu-west-1.amazonaws.com/genai/api
          FRONTEND_REPOSITORY_URI=533267242259.dkr.ecr.eu-west-1.amazonaws.com/genai/frontend

          docker buildx build --platform linux/amd64,linux/arm64 -t $API_REPOSITORY_URI:$IMAGE_TAG .
          docker buildx build --platform linux/amd64,linux/arm64 -t $FRONTEND_REPOSITORY_URI:$IMAGE_TAG .
          docker push $API_REPOSITORY_URI:$IMAGE_TAG
          docker push $FRONTEND_REPOSITORY_URI:$IMAGE_TAG
