name: Tenant Client Build

on:
  workflow_dispatch:
    inputs:
      tenants:
        description: 'Comma-separated list of tenants to build for (leave empty for all)'
        required: false
        default: ''
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'librechat-config/tenant-styles/**'

jobs:
  determine-tenants:
    runs-on: ubuntu-latest
    outputs:
      tenant-matrix: ${{ steps.set-matrix.outputs.tenant-matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: aproorg/librechat-config
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set tenant matrix
        id: set-matrix
        run: |
          if [ -n "${{ github.event.inputs.tenants }}" ]; then
            # Use manually specified tenants
            TENANTS=$(echo "${{ github.event.inputs.tenants }}" | tr ',' '\n' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          else
            # Discover tenants from directory structure
            TENANTS=$(find tenant-styles -mindepth 1 -maxdepth 1 -type d | sed 's|tenant-styles/||' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          fi
          echo "tenant-matrix=${TENANTS}" >> $GITHUB_OUTPUT

  build-client:
    needs: determine-tenants
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tenant: ${{ fromJson(needs.determine-tenants.outputs.tenant-matrix) }}
    steps:
      - name: Checkout LibreChat
        uses: actions/checkout@v4
        with:
          repository: aproorg/LibreChat
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout librechat-config
        uses: actions/checkout@v4
        with:
          repository: aproorg/librechat-config
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ../librechat-config
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build client for tenant
        env:
          TENANT: ${{ matrix.tenant }}
        run: |
          cd client
          npm ci
          npm run build
          
      - name: Upload client build
        uses: actions/upload-artifact@v4
        with:
          name: librechat-client-${{ matrix.tenant }}
          path: client/dist/${{ matrix.tenant || 'default' }}
          retention-days: 7
